"""core and bondlens

Revision ID: 4bb868b043d7
Revises: 
Create Date: 2026-08-28 22:05:34.209901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_core_and_bondlens'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmbs_deals',
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=True),
    sa.Column('asset_number', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_cik', sa.String(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('field_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmbs_filings',
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('primary_document', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['cmbs_deals.cik'], ),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_table('cmbs_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('asset_number', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('originator_name', sa.String(), nullable=True),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('original_loan_amount', sa.Numeric(), nullable=True),
    sa.Column('original_interest_rate_percentage', sa.Numeric(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('paid_through_date', sa.Date(), nullable=True),
    sa.Column('scheduled_principal_amount', sa.Numeric(), nullable=True),
    sa.Column('scheduled_interest_amount', sa.Numeric(), nullable=True),
    sa.Column('actual_balance_amount', sa.Numeric(), nullable=True),
    sa.Column('scheduled_balance_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_status_code', sa.String(), nullable=True),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accession_number'], ['cmbs_filings.accession_number'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'asset_number', name='uq_asset_accession_number')
    )
    op.create_table('cmbs_reporting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('beginning_date', sa.Date(), nullable=True),
    sa.Column('ending_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['accession_number'], ['cmbs_filings.accession_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', name='uq_reporting_period_accession')
    )
    op.create_table('cmbs_property_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('property_index', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('property_address', sa.String(), nullable=True),
    sa.Column('property_city', sa.String(), nullable=True),
    sa.Column('property_state', sa.String(), nullable=True),
    sa.Column('property_zip', sa.String(), nullable=True),
    sa.Column('property_county', sa.String(), nullable=True),
    sa.Column('property_type_code', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('net_rentable_square_feet', sa.Numeric(), nullable=True),
    sa.Column('at_securitization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('most_recent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['cmbs_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'property_index', name='uq_property_asset_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmbs_property_snapshots')
    op.drop_table('cmbs_reporting_periods')
    op.drop_table('cmbs_assets')
    op.drop_table('cmbs_filings')
    op.drop_table('source_documents')
    op.drop_table('ingestion_runs')
    op.drop_table('data_quality_issues')
    op.drop_table('cmbs_deals')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
